name: Deploy to Prod Server 

on:
  push:
    branches:
      - main

jobs:
  deploy_web_app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        max-parallel: [1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Add public IP to AWS security group for Web App
        uses: sohelamin/aws-security-group-add-ip-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-security-group-id: 'sg-05130a771d99793dc'
          port: '22'
          to-port: '22'
          protocol: 'tcp'
          description: 'GitHub Action'
            run: |
          aws s3 cp path/to/your/file s3://your-bucket-name/your-file-name
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
