name: Deploy  

on:
  push:
    branches:
      - main

jobs:
  deploy_web_app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        max-parallel: [1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Add public IP to AWS security group for Web App
       # uses: panku9/aws-security-group-add-ip-action@main
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-security-group-id: 'sg-00ffe05e1c7371f4b'
          port: '22'
          to-port: '22'
          protocol: 'tcp'
          description: 'GitHub Action'
          
      - name: Deploy to S3
        run: |
        
          aws s3 sync build/ "s3://$S3_BUCKET"

